//admin get phones
export const GET_PHONES = 'GET_PHONES'
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS'
export const GET_PHONES_FAIL = 'GET_PHONES_FAIL'

//admin add phone
export const ADMIN_ADD_PHONE = 'ADMIN_ADD_PHONE'
export const ADMIN_ADD_PHONE_SUCCESS = 'ADMIN_ADD_PHONE_SUCCESS'
export const ADMIN_ADD_PHONE_FAIL = 'ADMIN_ADD_PHONE_FAIL'

//admin delete phone
export const ADMIN_DELETE_PHONE = 'ADMIN_DELETE_PHONE'
export const ADMIN_DELETE_PHONE_SUCCESS = 'ADMIN_DELETE_PHONE_SUCCESS'
export const ADMIN_DELETE_PHONE_FAIL = 'ADMIN_DELETE_PHONE_FAIL'

//admin edit phone
export const ADMIN_EDIT_PHONE = 'ADMIN_EDIT_PHONE'
export const ADMIN_EDIT_PHONE_SUCCESS = 'ADMIN_EDIT_PHONE_SUCCESS'
export const ADMIN_EDIT_PHONE_FAIL = 'ADMIN_EDIT_PHONE_FAIL'
